---
abstract: 'Transparently perform statistics on IO handles'
author:
  - 'Chia-liang Kao <clkao@clkao.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IO-Statistics
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  PerlIO::via::dynamic: 0.10
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/clkao/IO-Statistics.git
version: 0.13
